# Generated by Django 3.1.1 on 2020-11-23 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=1024, verbose_name='Address line 1')),
                ('street_name', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=1024, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=5, verbose_name='ZIP / Postal code')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=500)),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='date and start time')),
                ('event_duration', models.IntegerField(default=1)),
                ('event_endtime', models.DateTimeField(blank=True, null=True)),
                ('event_capacity', models.IntegerField(default=10)),
                ('event_public', models.BooleanField(default=True)),
                ('event_tags', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
                ('event_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='MainApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=200)),
                ('groups', models.ManyToManyField(related_name='people', through='MainApp.GroupMember', to='MainApp.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='MainApp.profile'),
        ),
    ]
